name: Shorten URL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # Add more events as needed, e.g., schedule, or repository_dispatch

jobs:
  shorten_url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt
        # You may need to add this step based on your dependencies

      - name: Execute Python script
        run: python scripts/shorten_url_script.py
        env:
          AIRTABLE_API_KEY: ${{ patIqzBAoDQ4bb39N.528fc2b11ece2f6feee104a5a422ba08406b0a6b8e4880365308c80bdc6de40e }}
          AIRTABLE_BASE_ID: ${{ appUl6O6X3FT8SwnE }}
          AIRTABLE_TABLE_NAME: '👥 고객관리 DB'
          BITLY_ACCESS_TOKEN: ${{ secrets.BITLY_ACCESS_TOKEN }}
